PVP: 200 # Time in ticks. After hitting a player during this time, this player cannot be used
         # commands that have FEASIBILITY_IN_PVP = false.

DROP_TROLL:
  ENABLE: true
  COOLDOWN: 600 # In seconds
  FEASIBILITY_IN_PVP: false # Can it be applied to a player if he is in pvp. false - if it is impossible, true - if it is possible

DRUNK_TROLL:
  ENABLE: true
  COOLDOWN: 600 # In seconds
  FEASIBILITY_IN_PVP: false # Can it be applied to a player if he is in pvp. false - if it is impossible, true - if it is possible
  POTIONS:
    POISON:
      DURATION: 100 # Duration, in ticks.
      LVL: 1 # Level.
    CONFUSION:
      DURATION: 100
      LVL: 1

HEALL_TROLL:
  ENABLE: true
  COOLDOWN: 600 # In seconds
  FEASIBILITY_IN_PVP: false # Can it be applied to a player if he is in pvp. false - if it is impossible, true - if it is possible
  AMOUNT: 4 # How many hearts will this team remove.

LIFT_TROLL:
  ENABLE: true
  COOLDOWN: 600 # In seconds
  FEASIBILITY_IN_PVP: false # Can it be applied to a player if he is in pvp. false - if it is impossible, true - if it is possible
  JUMP: 1 # The force of the upward thrust.

OP_TROLL:
  ENABLE: true
  COOLDOWN: 600 # In seconds
  FEASIBILITY_IN_PVP: true # Can it be applied to a player if he is in pvp. false - if it is impossible, true - if it is possible

PAY_TROLL:
  ENABLE: true
  COOLDOWN: 600 # In seconds
  FEASIBILITY_IN_PVP: true # Can it be applied to a player if he is in pvp. false - if it is impossible, true - if it is possible

ROTATE_TROLL:
  ENABLE: true
  COOLDOWN: 600 # In seconds
  FEASIBILITY_IN_PVP: false # Can it be applied to a player if he is in pvp. false - if it is impossible, true - if it is possible
  AMOUNT: 2 # The number of iterations. In one iteration, the head turns 5 degrees. The iteration period is 1 tick.

SLAP_TROLL:
  ENABLE: true
  COOLDOWN: 600 # In seconds
  FEASIBILITY_IN_PVP: false # Can it be applied to a player if he is in pvp. false - if it is impossible, true - if it is possible
  STRENGTH: 10 # The player's drop power. If you specify a positive number, the player will lean forward. Negative - back.
  Y_STRENGTH: 0.5 # The strength of the player's discarding by y. It is better to specify only positive numbers.

SPAM_TROLL:
  ENABLE: true
  COOLDOWN: 600 # In seconds
  FEASIBILITY_IN_PVP: true # Can it be applied to a player if he is in pvp. false - if it is impossible, true - if it is possible.
  AMOUNT: 20 # Amount messages
  PERIOD: 3 # Periodicity. In ticks.
  # CONFIGURING MESSAGES FOR SPAM IN messages.yml!

STARVE_TROLL:
  ENABLE: true
  COOLDOWN: 600 # In seconds
  FEASIBILITY_IN_PVP: false # Can it be applied to a player if he is in pvp. false - if it is impossible, true - if it is possible
  NEW_LEVEL: 2 # The level of food that will be set to the player after applying the command.

SOUND_TROLL:
  ENABLE: true
  COOLDOWN: 600 # In seconds
  FEASIBILITY_IN_PVP: true # Can it be applied to a player if he is in pvp. false - if it is impossible, true - if it is possible

BURN_TROLL:
  ENABLE: true
  COOLDOWN: 600 # In seconds
  FEASIBILITY_IN_PVP: false # Can it be applied to a player if he is in pvp. false - if it is impossible, true - if it is possible
  FIRE_TICKS: 200 # In ticks. For how long the player will be on fire.